insert into UF values(1, 'Acre', 'AC', 1)
insert into UF values(2, 'Alagoas', 'AL', 1)
insert into UF values(3, 'Amazonas', 'AM', 1)
insert into UF values(4, 'Amapá', 'AP', 1)
insert into UF values(5, 'Bahia', 'BA', 1)
insert into UF values(6, 'Ceará', 'CE', 1)
insert into UF values(7, 'Distrito Federal', 'DF', 1)
insert into UF values(8, 'Espírito Santo', 'ES', 1)
insert into UF values(9, 'Goiás', 'GO', 1)
insert into UF values(10, 'Maranhão', 'MA', 1)
insert into UF values(11, 'Minas Gerais', 'MG', 1)
insert into UF values(12, 'Mato Grosso do Sul', 'MS', 1)
insert into UF values(13, 'Mato Grosso', 'MT', 1)
insert into UF values(14, 'Pará', 'PA', 1)
insert into UF values(15, 'Paraíba', 'PB', 1)
insert into UF values(16, 'Pernambuco', 'PE', 1)
insert into UF values(17, 'Piauí', 'PI', 1)
insert into UF values(18, 'Paraná', 'PR', 1)
insert into UF values(19, 'Rio de Janeiro', 'RJ', 1)
insert into UF values(20, 'Rio Grande do Norte', 'RN', 1)
insert into UF values(21, 'Rondônia', 'RO', 1)
insert into UF values(22, 'Roraima', 'RR', 1)
insert into UF values(23, 'Rio Grande do Sul', 'RS', 1)
insert into UF values(24, 'Santa Catarina', 'SC', 1)
insert into UF values(25, 'Sergipe', 'SE', 1)
insert into UF values(26, 'São Paulo', 'SP', 1)
insert into UF values(27, 'Tocantins', 'TO', 1)